name: knee-seg-1.0
channels:
  - conda-forge
dependencies:
  - hdbscan
  - matplotlib
  - numpy
  - opencv
  - openpyxl
  - pandas
  - pip
  - python=3.11
  - scikit-learn
  - tifffile
  - pip:
    - knee-segmentation==0.1

prefix: "C:\\Users\\olimoon\\.local\\share\\mamba\\envs\\knee-seg-1.0"
