[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "knee-segmentation"
version = "0.1"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]